# Generated by Django 5.2.8 on 2026-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="view_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
