# Generated by Django 5.2.8 on 2026-04-22 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0002_alter_questions_view_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Answers",
            new_name="Answer",
        ),
        migrations.RenameModel(
            old_name="AnswerComments",
            new_name="AnswerComment",
        ),
        migrations.RenameModel(
            old_name="AnswerImages",
            new_name="AnswerImage",
        ),
        migrations.RenameModel(
            old_name="Questions",
            new_name="Question",
        ),
        migrations.RenameModel(
            old_name="QuestionCategories",
            new_name="QuestionCategorie",
        ),
        migrations.RenameModel(
            old_name="QuestionImages",
            new_name="QuestionImage",
        ),
        migrations.AlterModelTable(
            name="answer",
            table="answer",
        ),
        migrations.AlterModelTable(
            name="answercomment",
            table="answer_comment",
        ),
        migrations.AlterModelTable(
            name="answerimage",
            table="answer_image",
        ),
        migrations.AlterModelTable(
            name="question",
            table="question",
        ),
        migrations.AlterModelTable(
            name="questioncategorie",
            table="question_categorie",
        ),
    ]
