# Generated by Django 5.2.8 on 2026-04-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0003_rename_answers_answer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuestionCategorie",
            new_name="QuestionCategory",
        ),
        migrations.AlterModelTable(
            name="question",
            table="questions",
        ),
        migrations.AlterModelTable(
            name="questioncategory",
            table="question_categories",
        ),
    ]
