# Generated by Django 5.2.8 on 2026-04-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="status",
            field=models.CharField(
                choices=[("PREPARING", "준비중"), ("IN_PROGRESS", "진행중"), ("FINISHED", "종료")],
                default="PREPARING",
                max_length=20,
            ),
        ),
    ]
