# Generated by Django 5.2.8 on 2026-05-15 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_cohort_status"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Course",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("name", models.CharField(max_length=30, unique=True)),
                        ("tag", models.CharField(max_length=3, unique=True)),
                        ("description", models.CharField(blank=True, max_length=255, null=True)),
                        ("thumbnail_img_url", models.CharField(blank=True, max_length=255, null=True)),
                    ],
                    options={
                        "db_table": "courses",
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="cohort",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cohorts", to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="subjects", to="courses.course"
            ),
        ),
    ]
