# Generated by Django 5.2.8 on 2026-04-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role_alter_withdrawal_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("USER", "일반유저"), ("ADMIN", "어드민"), ("STUDENT", "수강생")], default="USER"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="reason",
            field=models.CharField(
                choices=[
                    ("graduation", "졸업"),
                    ("transfer", "다른 플랫폼 이동"),
                    ("no_longer_needed", "더 이상 필요없음"),
                    ("lack_of_interest", "흥미 떨어짐"),
                    ("too_difficult", "너무 어려움"),
                    ("found_better_service", "더 좋은 서비스 찾음"),
                    ("privacy_concerns", "개인정보 우려"),
                    ("poor_service_quality", "서비스 품질 불만"),
                    ("technical_issue", "기술적 문제"),
                    ("lack_of_content", "콘텐츠 부족"),
                    ("other", "기타"),
                ],
                max_length=20,
            ),
        ),
    ]
