# Generated by Django 5.2.8 on 2026-04-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_active_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialusers",
            name="provider_id",
            field=models.CharField(max_length=255),
        ),
    ]
