# Generated by Django 5.2.8 on 2026-04-22 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_socialusers_provider_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="reason_detail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
