# Generated by Django 5.2.8 on 2026-04-23 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_withdrawal_reason_detail_alter_withdrawal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="reason_detail",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="user",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawals",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
