# Generated by Django 5.2.8 on 2026-04-23 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_is_active_alter_withdrawal_reason_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
