# Generated by Django 5.2.8 on 2026-04-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_course_thumbnail_img_url_alter_cohort_status_and_more"),
        ("users", "0007_alter_withdrawal_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohortstudents",
            name="cohort",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.cohort"),
        ),
        migrations.AddField(
            model_name="learningcoachs",
            name="course",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.course"),
        ),
        migrations.AddField(
            model_name="operationmanagers",
            name="course",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.course"),
        ),
        migrations.AddField(
            model_name="studentenrollmentrequests",
            name="cohort",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.cohort"),
        ),
        migrations.AddField(
            model_name="trainigassistants",
            name="cohort",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.cohort"),
        ),
        migrations.AlterField(
            model_name="studentenrollmentrequests",
            name="status",
            field=models.CharField(
                choices=[("pending", "대기중"), ("accepted", "승인됨"), ("rejected", "거절됨"), ("canceled", "취소됨")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(choices=[("M", "남성"), ("F", "여성")], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("USER", "일반유저"), ("ADMIN", "관리자"), ("STUDENT", "수강생")], default="USER"
            ),
        ),
    ]
