# Generated by Django 5.2.8 on 2026-04-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_withdrawal_reason_detail_alter_withdrawal_user"),
        ("users", "0008_cohortstudents_cohort_learningcoachs_course_and_more"),
    ]

    operations = []
