# Generated by Django 5.2.8 on 2026-04-29 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0008_cohortstudents_cohort_learningcoachs_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohortstudents",
            name="cohort",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="courses.cohort"),
        ),
        migrations.AlterField(
            model_name="studentenrollmentrequests",
            name="cohort",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="courses.cohort"),
        ),
        migrations.AlterField(
            model_name="trainigassistants",
            name="cohort",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="courses.cohort"),
        ),
    ]
