# Generated by Django 5.2.8 on 2026-04-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_cohortstudents_cohort_and_more"),
        ("users", "0009_merge_20260429_1132"),
    ]

    operations = []
