# Generated by Django 5.2.8 on 2026-04-30 11:45

from pathlib import Path

from django.db import migrations

dependencies = [
    ("users", "0010_merge_20260429_2021"),
]

if Path(__file__).with_name("0010_merge_20260430_1057.py").exists():
    dependencies.append(("users", "0010_merge_20260430_1057"))


class Migration(migrations.Migration):

    dependencies = dependencies

    operations = []
