# Generated by Django 5.2.8 on 2026-05-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_merge_20260430_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="reason",
            field=models.CharField(
                choices=[
                    ("GRADUATION", "졸업"),
                    ("TRANSFER", "다른 플랫폼 이동"),
                    ("NO_LONGER_NEEDED", "더 이상 필요하지 않음"),
                    ("LACK_OF_INTEREST", "흥미 떨어짐"),
                    ("TOO_DIFFICULT", "너무 어려움"),
                    ("FOUND_BETTER_SERVICE", "더 좋은 서비스 찾음"),
                    ("PRIVACY_CONCERNS", "개인정보 우려"),
                    ("POOR_SERVICE_QUALITY", "서비스 품질 불만"),
                    ("TECHNICAL_ISSUES", "기술적 문제"),
                    ("LACK_OF_CONTENT", "콘텐츠 부족"),
                    ("OTHER", "기타"),
                ],
                max_length=20,
            ),
        ),
    ]
