# Generated by Django 5.2.8 on 2026-05-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_merge_20260430_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
