# Generated by Django 5.2.8 on 2026-05-15 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_alter_cohort_course_alter_subject_course"),
        ("users", "0013_merge_20260513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningcoachs",
            name="course",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="courses.course"),
        ),
        migrations.AlterField(
            model_name="operationmanagers",
            name="course",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="courses.course"),
        ),
    ]
