# Generated by Django 5.2.8 on 2026-04-21 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_alter_examquestion_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examdeployment",
            name="duration_time",
            field=models.SmallIntegerField(
                default=60,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="blank_count",
            field=models.SmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)],
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="point",
            field=models.SmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="examsubmission",
            name="cheating_count",
            field=models.SmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="examsubmission",
            name="correct_answer_count",
            field=models.SmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="examsubmission",
            name="score",
            field=models.SmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
