# Generated by Django 5.2.8 on 2026-04-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_alter_examdeployment_duration_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examquestion",
            old_name="explantation",
            new_name="explanation",
        ),
    ]
