# Generated by Django 5.2.8 on 2026-04-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_rename_explantation_examquestion_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("blank", "빈칸채우기"),
                    ("sort", "순서정렬"),
                    ("choice", "다지선다"),
                    ("word", "단답형"),
                    ("quiz", "OX퀴즈"),
                ],
                max_length=10,
            ),
        ),
    ]
