# Generated by Django 5.2.8 on 2026-04-22 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_alter_examquestion_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examdeployment",
            name="close_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="examdeployment",
            name="open_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
