# Generated by Django 5.2.8 on 2026-04-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_alter_examdeployment_close_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examdeployment",
            name="access_code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="examdeployment",
            name="status",
            field=models.CharField(
                choices=[("activate", "활성화"), ("deactivate", "비활성화")], default="activate", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("fill_blank", "빈칸채우기"),
                    ("ordering", "순서정렬"),
                    ("multiple_choice", "다지선다(복수선택)"),
                    ("single_choice", "다지선다(단일선택)"),
                    ("short_answer", "단답형"),
                    ("ox", "OX퀴즈"),
                ],
                max_length=20,
            ),
        ),
    ]
