# Generated by Django 5.2.8 on 2026-04-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_alter_examdeployment_access_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examdeployment",
            old_name="question_snapshot_json",
            new_name="questions_snapshot_json",
        ),
        migrations.RenameField(
            model_name="examquestion",
            old_name="optional_json",
            new_name="options_json",
        ),
    ]
