# Generated by Django 5.2.8 on 2026-04-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0009_rename_question_snapshot_json_examdeployment_questions_snapshot_json_and_more"),
        ("posts", "0008_course_thumbnail_img_url_alter_cohort_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["-created_at", "title"]},
        ),
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="exams", to="posts.subject"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
