# Generated by Django 5.2.8 on 2026-04-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0009_rename_question_snapshot_json_examdeployment_questions_snapshot_json_and_more"),
        ("posts", "0008_course_thumbnail_img_url_alter_cohort_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="posts.subject"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examdeployment",
            name="cohort",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="posts.cohort"),
            preserve_default=False,
        ),
    ]
