# Generated by Django 5.2.8 on 2026-04-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_exam_subject_examdeployment_cohort"),
        ("posts", "0008_course_thumbnail_img_url_alter_cohort_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examdeployment",
            unique_together={("exam", "cohort")},
        ),
    ]
