# Generated by Django 5.2.8 on 2026-04-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0011_alter_examdeployment_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="thumbnail_image_url",
            new_name="thumbnail_img_url",
        ),
        migrations.AlterField(
            model_name="examdeployment",
            name="status",
            field=models.CharField(
                choices=[("Activated", "활성화"), ("Deactivated", "비활성화")], default="Activated", max_length=11
            ),
        ),
    ]
