# Generated by Django 5.2.8 on 2026-04-29 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("exams", "0011_alter_examdeployment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="exams", to="courses.subject"
            ),
        ),
        migrations.AlterField(
            model_name="examdeployment",
            name="cohort",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.cohort"),
        ),
    ]
