# Generated by Django 5.2.8 on 2026-04-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0012_alter_exam_subject_alter_examdeployment_cohort"),
        ("exams", "0012_rename_thumbnail_image_url_exam_thumbnail_img_url_and_more"),
    ]

    operations = []
