# Generated by Django 5.2.8 on 2026-05-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0013_merge_20260430_1057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="answer",
            field=models.JSONField(default=list),
        ),
    ]
