# Generated by Django 5.2.8 on 2026-04-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcategory",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
