# Generated by Django 5.2.1 on 2026-04-22 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_postcomment_postcommenttag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomment",
            name="content",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name="postcommenttag",
            unique_together={("comment", "tagged_user")},
        ),
    ]
