# Generated by Django 5.2.8 on 2026-04-23 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["post", "is_liked"], name="idx_post_is_liked"),
        ),
    ]
