# Generated by Django 5.2.8 on 2026-04-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_course_cohort_subject"),
        ("posts", "0006_like_idx_post_is_liked"),
    ]

    operations = []
