# Generated by Django 5.2.8 on 2026-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_merge_20260423_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="thumbnail_img_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="status",
            field=models.CharField(
                choices=[("SUBMITTED", "대기"), ("ACCEPTED", "승인"), ("REJECTED", "거절")],
                default="SUBMITTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
