# Generated by Django 5.2.8 on 2026-04-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0012_alter_exam_subject_alter_examdeployment_cohort"),
        ("posts", "0008_course_thumbnail_img_url_alter_cohort_status_and_more"),
        ("users", "0009_alter_cohortstudents_cohort_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="subject",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="subject",
                    name="course",
                ),
                migrations.DeleteModel(
                    name="Cohort",
                ),
                migrations.DeleteModel(
                    name="Subject",
                ),
            ],
            database_operations=[],
        ),
    ]
