# Generated by Django 5.2.8 on 2026-05-15 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_alter_cohort_course_alter_subject_course"),
        ("posts", "0010_notification"),
        ("users", "0014_alter_learningcoachs_course_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.AddField(
            model_name="postcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="posts.postcomment",
            ),
        ),
    ]
